sudo: required
env:
  - CXX=g++-5
language: node_js
node_js:
  - "7"
before_install:
  - npm install -g webpack node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-4.8